(cl:in-package plan_msgs-msg)
(cl:export '(T-VAL
          T
          D-VAL
          D
          D_D-VAL
          D_D
          D_DD-VAL
          D_DD
          D_DDD-VAL
          D_DDD
          S-VAL
          S
          S_D-VAL
          S_D
          S_DD-VAL
          S_DD
          S_DDD-VAL
          S_DDD
          X-VAL
          X
          Y-VAL
          Y
          YAW-VAL
          YAW
          KS-VAL
          KS
          LX-VAL
          LX
          LY-VAL
          LY
          LYAW-VAL
          LYAW
))