(cl:in-package plan_msgs-msg)
(cl:export '(STAMP-VAL
          STAMP
          E_STOP-VAL
          E_STOP
          SPEED-VAL
          SPEED
          ANG_VELO-VAL
          ANG_VELO
          DISTANCE-VAL
          DISTANCE
          ANGLE-VAL
          ANGLE
          CONTROL_FLAG-VAL
          CONTROL_FLAG
          ACTION_FLAG-VAL
          ACTION_FLAG
          MITION_NUM-VAL
          MITION_NUM
          MITION_POINT_X-VAL
          MITION_POINT_X
          MITION_POINT_Y-VAL
          MITION_POINT_Y
          MITION_POINT_SPEED-VAL
          MITION_POINT_SPEED
          MITION_POINT_A-VAL
          MITION_POINT_A
          ORIGIN_X-VAL
          ORIGIN_X
          ORIGIN_Y-VAL
          ORIGIN_Y
          ORIGIN_Z-VAL
          ORIGIN_Z
          ORIGIN_YAW-VAL
          ORIGIN_YAW
          MITION_FINISH-VAL
          MITION_FINISH
))