// Generated by gencpp from file cloud_msgs/PointXYA.msg
// DO NOT EDIT!


#ifndef CLOUD_MSGS_MESSAGE_POINTXYA_H
#define CLOUD_MSGS_MESSAGE_POINTXYA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cloud_msgs
{
template <class ContainerAllocator>
struct PointXYA_
{
  typedef PointXYA_<ContainerAllocator> Type;

  PointXYA_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  PointXYA_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::cloud_msgs::PointXYA_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cloud_msgs::PointXYA_<ContainerAllocator> const> ConstPtr;

}; // struct PointXYA_

typedef ::cloud_msgs::PointXYA_<std::allocator<void> > PointXYA;

typedef boost::shared_ptr< ::cloud_msgs::PointXYA > PointXYAPtr;
typedef boost::shared_ptr< ::cloud_msgs::PointXYA const> PointXYAConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cloud_msgs::PointXYA_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cloud_msgs::PointXYA_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cloud_msgs::PointXYA_<ContainerAllocator1> & lhs, const ::cloud_msgs::PointXYA_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cloud_msgs::PointXYA_<ContainerAllocator1> & lhs, const ::cloud_msgs::PointXYA_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cloud_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cloud_msgs::PointXYA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cloud_msgs::PointXYA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_msgs::PointXYA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_msgs::PointXYA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_msgs::PointXYA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_msgs::PointXYA_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cloud_msgs::PointXYA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b71344c0ba01936756dc45bcd89ef437";
  }

  static const char* value(const ::cloud_msgs::PointXYA_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb71344c0ba019367ULL;
  static const uint64_t static_value2 = 0x56dc45bcd89ef437ULL;
};

template<class ContainerAllocator>
struct DataType< ::cloud_msgs::PointXYA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cloud_msgs/PointXYA";
  }

  static const char* value(const ::cloud_msgs::PointXYA_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cloud_msgs::PointXYA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 yaw  # degs\n"
;
  }

  static const char* value(const ::cloud_msgs::PointXYA_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cloud_msgs::PointXYA_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointXYA_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cloud_msgs::PointXYA_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cloud_msgs::PointXYA_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOUD_MSGS_MESSAGE_POINTXYA_H
