time stamp                                                      #当前时间
int32 width                                                     #宽度分片数，左→右
int32 height                                                    #远近分片数，近→远
int32 size
int32[] value                                                  #路面分片的矩阵
float32 d_width                                                 #格网分辨率
float32 d_height                                                #格网分辨率
