// Generated by gencpp from file plan_msgs/Traj.msg
// DO NOT EDIT!


#ifndef PLAN_MSGS_MESSAGE_TRAJ_H
#define PLAN_MSGS_MESSAGE_TRAJ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <plan_msgs/PointTraj.h>

namespace plan_msgs
{
template <class ContainerAllocator>
struct Traj_
{
  typedef Traj_<ContainerAllocator> Type;

  Traj_()
    : num(0)
    , points()  {
    }
  Traj_(const ContainerAllocator& _alloc)
    : num(0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _num_type;
  _num_type num;

   typedef std::vector< ::plan_msgs::PointTraj_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::plan_msgs::PointTraj_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::plan_msgs::Traj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plan_msgs::Traj_<ContainerAllocator> const> ConstPtr;

}; // struct Traj_

typedef ::plan_msgs::Traj_<std::allocator<void> > Traj;

typedef boost::shared_ptr< ::plan_msgs::Traj > TrajPtr;
typedef boost::shared_ptr< ::plan_msgs::Traj const> TrajConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plan_msgs::Traj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plan_msgs::Traj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plan_msgs::Traj_<ContainerAllocator1> & lhs, const ::plan_msgs::Traj_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plan_msgs::Traj_<ContainerAllocator1> & lhs, const ::plan_msgs::Traj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plan_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plan_msgs::Traj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_msgs::Traj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_msgs::Traj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_msgs::Traj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_msgs::Traj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_msgs::Traj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plan_msgs::Traj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "490cb3b1cf624497cbfba91636b0dd01";
  }

  static const char* value(const ::plan_msgs::Traj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x490cb3b1cf624497ULL;
  static const uint64_t static_value2 = 0xcbfba91636b0dd01ULL;
};

template<class ContainerAllocator>
struct DataType< ::plan_msgs::Traj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plan_msgs/Traj";
  }

  static const char* value(const ::plan_msgs::Traj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plan_msgs::Traj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32     num\n"
"PointTraj[]  points\n"
"\n"
"================================================================================\n"
"MSG: plan_msgs/PointTraj\n"
"int32 t\n"
"float32 d\n"
"float32 d_d\n"
"float32 d_dd\n"
"float32 d_ddd\n"
"float32 s\n"
"float32 s_d\n"
"float32 s_dd\n"
"float32 s_ddd\n"
"float32 x\n"
"float32 y\n"
"float32 yaw\n"
"float32 ks\n"
"float32 lx\n"
"float32 ly\n"
"float32 lyaw\n"
;
  }

  static const char* value(const ::plan_msgs::Traj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plan_msgs::Traj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Traj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plan_msgs::Traj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plan_msgs::Traj_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::plan_msgs::PointTraj_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAN_MSGS_MESSAGE_TRAJ_H
